# Generated by Django 4.1.3 on 2022-11-12 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('E', 'Expense'), ('I', 'Incame'), ('T', 'Transfer')], max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('E', 'Expense'), ('I', 'Incame'), ('T', 'Transfer')], max_length=2)),
                ('status', models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('description', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(to='cashflow.account')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cashflow.category')),
            ],
        ),
    ]
